import test, {after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {db,closeDb} from '../lib/server/db.ts';
import {adminCommand} from '../lib/server/admin.ts';
const directory=fs.mkdtempSync(path.join(os.tmpdir(),'policy-continuation-'));
Object.assign(process.env,{DATA_DIR:directory,NODE_ENV:'test',MAIL_TRANSPORT:'file',APP_URL:'https://offline.example'});
after(()=>{closeDb();fs.rmSync(directory,{recursive:true,force:true});});
test('current-method continuation preserves frozen pilot, researches three inputs and requires new approval',async()=>{
  const now=new Date().toISOString();
  db().prepare('INSERT INTO users (id,email,name,created_at,verified_at) VALUES (?,?,?,?,?)').run('owner','owner@offline-fixture.example','Offline Owner',now,now);
  const providers=[{name:'Fixture',website:'https://fixture.example/',customers:[1,2,3].map(n=>({name:`Store ${n}`,website:`https://store-${n}.example/`}))}];
  const protocol=JSON.stringify({id:'quality-pilot-v1',sha256:'offline-fixture'});
  db().prepare("INSERT INTO requests (id,user_id,providers_json,status,created_at,updated_at,review_token_hash,review_expires_at,review_decision,reviewed_at,attribution_confirmed_at,protocol_json) VALUES ('legacy','owner',?,'needs_review',?,?,'offline',?,'approve',?,?,?)").run(JSON.stringify(providers),now,now,Date.now()+600000,now,now,protocol);
  db().prepare("INSERT INTO jobs (id,request_id,state,protocol_json,available_at,created_at,updated_at) VALUES ('legacy-job','legacy','needs_review',?,?,?,?)").run(protocol,Date.now(),now,now);
  const before=db().prepare("SELECT * FROM requests WHERE id='legacy'").get();
  const result=await adminCommand('prepare-current','legacy') as any;
  assert.equal(result.status,'researching');
  const newRow=db().prepare('SELECT * FROM requests WHERE id=?').get(result.requestId) as any;
  assert.equal(newRow.review_decision,null);assert.equal(newRow.reviewed_at,null);assert.equal(JSON.parse(newRow.protocol_json).id,'policy-resolution-v1');
  assert.deepEqual(JSON.parse(newRow.providers_json),providers);assert.deepEqual(db().prepare("SELECT * FROM requests WHERE id='legacy'").get(),before);
  assert.equal((db().prepare('SELECT COUNT(*) n FROM jobs').get() as any).n,1);
  assert.equal((db().prepare('SELECT state FROM preparation_jobs WHERE request_id=?').get(result.requestId) as any).state,'queued');
  assert.equal((await adminCommand('prepare-current','legacy') as any).requestId,result.requestId);
  assert.equal((db().prepare('SELECT COUNT(*) n FROM preparation_jobs').get() as any).n,1);
  assert.equal((db().prepare('SELECT COUNT(*) n FROM outbox').get() as any).n,1);
  db().prepare("UPDATE preparation_jobs SET state='needs_review' WHERE request_id=?").run(result.requestId);
  await adminCommand('retry-research',result.requestId);
  assert.equal((db().prepare('SELECT state FROM preparation_jobs WHERE request_id=?').get(result.requestId) as any).state,'queued');
  await assert.rejects(()=>adminCommand('retry',result.requestId),/approved/);
  await assert.rejects(()=>adminCommand('retry-research',result.requestId),/stopped/);
});
