import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {db,closeDb} from '../lib/server/db.ts';
import {adminCommand} from '../lib/server/admin.ts';
import {priorRosterApprovals} from '../lib/server/roster-amendments.ts';
import {policyProtocol} from '../lib/server/policy-automation.ts';
import {handleApi} from '../lib/server/api.ts';
import {hash} from '../lib/server/security.ts';
import {evidenceDateValidator} from '../worker/policy-evidence.mjs';
import {merchantId} from '../worker/policy-contract.mjs';
const directory=fs.mkdtempSync(path.join(os.tmpdir(),'roster-amendment-'));
Object.assign(process.env,{DATA_DIR:directory,NODE_ENV:'test',MAIL_TRANSPORT:'file',APP_URL:'http://localhost:3000',WORKER_SECRET:'offline-worker-secret-at-least-32-characters'});
after(()=>{closeDb();fs.rmSync(directory,{recursive:true,force:true});});
const provider={name:'Offline Tool',website:'https://tool.example/',customers:[1,2,3,4,5].map(n=>({name:`Fixture ${n}`,website:`https://store${n}.example/`}))};
const row=()=>db().prepare("SELECT * FROM requests WHERE id='request'").get() as any;
const job=()=>db().prepare("SELECT * FROM jobs WHERE id='job'").get() as any;
async function call(route:string,body:any,worker=false){const r=await handleApi(new Request(`${process.env.APP_URL}/api/${route}`,{method:'POST',headers:{origin:process.env.APP_URL!,'content-type':'application/json',...(worker?{authorization:`Bearer ${process.env.WORKER_SECRET}`}:{})},body:JSON.stringify(body)}));return {status:r.status,data:await r.json() as any};}
test('correcting an approved stopped roster archives approval and resumes the same job only after fresh review',async()=>{
 const old=new Date(Date.now()-3600000).toISOString(),protocol=JSON.stringify(policyProtocol());
 db().prepare("INSERT INTO users (id,email,name,created_at,verified_at) VALUES ('owner','offline@business.example','Offline Owner',?,?)").run(old,old);
 db().prepare("INSERT INTO requests (id,user_id,providers_json,status,created_at,updated_at,review_token_hash,review_expires_at,review_decision,reviewed_at,attribution_confirmed_at,protocol_json) VALUES ('request','owner',?,'needs_review',?,?,'old-token',?,'approve',?,?,?)").run(JSON.stringify([provider]),old,old,Date.now()+100000,old,old,protocol);
 db().prepare("INSERT INTO jobs (id,request_id,state,protocol_json,available_at,created_at,updated_at) VALUES ('job','request','needs_review',?,?,?,?)").run(protocol,Date.now(),old,old);
 db().prepare("INSERT INTO preparation_jobs (id,request_id,state,available_at,created_at,updated_at,completion_hash) VALUES ('prep','request','prepared',?,?,?,'old-evidence-hash')").run(Date.now(),old,old);
 const original=row(),result=await adminCommand('correct-roster','request') as any;
 assert.equal(result.jobId,'job');assert.equal(row().reviewed_at,null);assert.equal(row().review_decision,null);assert.equal(JSON.parse(row().providers_json)[0].customers.length,3);
 assert.equal(job().state,'awaiting_roster_approval');assert.deepEqual(priorRosterApprovals(row(),job()),[]);
 const archive=db().prepare('SELECT * FROM roster_amendments').get() as any;
 assert.equal(hash(archive.snapshot_json),archive.snapshot_sha256);assert.deepEqual(JSON.parse(archive.snapshot_json).request,{...original});assert.equal(JSON.parse(archive.snapshot_json).preparation.completion_hash,'old-evidence-hash');
 assert.equal((await call('worker/claim',{},true)).data.job,null);await assert.rejects(()=>adminCommand('retry','request'),/approved/);
 const token='offline-corrected-review-token-long-enough-for-validation';db().prepare('UPDATE requests SET review_token_hash=? WHERE id=?').run(hash(token),'request');
 assert.equal((await call(`review/${token}`,{decision:'approve',confirmAttribution:true})).status,409);
 const corrected=structuredClone(provider);corrected.customers[3]={name:'Replacement 4',website:'https://new4.example/'};corrected.customers[4]={name:'Replacement 5',website:'https://new5.example/'};
 db().prepare("UPDATE requests SET providers_json=?,status='pending_review' WHERE id='request'").run(JSON.stringify([corrected]));
 assert.equal((await call(`review/${token}`,{decision:'approve',confirmAttribution:true})).status,200);
 assert.equal((await call(`review/${token}`,{decision:'approve',confirmAttribution:true})).status,200);
 assert.equal((db().prepare('SELECT COUNT(*) n FROM jobs').get() as any).n,1);assert.equal(job().state,'queued');assert.notEqual(row().reviewed_at,old);
 const approvals=priorRosterApprovals(row(),job());assert.equal(approvals.length,3);assert.ok(approvals.every(a=>a.approvedAt===old));
 const claimed=await call('worker/claim',{},true);assert.equal(claimed.data.job.id,'job');assert.deepEqual(claimed.data.job.priorApprovals,approvals);
 const modified={...row(),providers_json:JSON.stringify([{...corrected,customers:corrected.customers.map((s,i)=>i===0?{...s,name:'Different identity'}:s)}])};
 assert.equal(priorRosterApprovals(modified,job()).length,2);assert.equal(priorRosterApprovals({...row(),protocol_json:'{}'},job()).length,0);
 const validate=evidenceDateValidator({providers:[corrected],protocolSnapshotSha256:policyProtocol().sha256,approvedAt:row().reviewed_at,priorApprovals:approvals});
 validate(old,false,merchantId(corrected.customers[0]));assert.throws(()=>validate(old,false,merchantId(corrected.customers[3])),/date range/);
 assert.throws(()=>validate(new Date(Date.now()-31*86400000).toISOString(),false,merchantId(corrected.customers[0])),/date range/);
 const delayedApproval=new Date(Date.now()+3600000).toISOString();
 const gapValidator=evidenceDateValidator({providers:[corrected],protocolSnapshotSha256:policyProtocol().sha256,approvedAt:delayedApproval,priorApprovals:approvals,now:new Date(Date.now()+7200000)});
 assert.throws(()=>gapValidator(new Date(Date.parse(archive.created_at)+1000).toISOString(),false,merchantId(corrected.customers[0])),/date range/);
 assert.throws(()=>evidenceDateValidator({providers:[corrected],protocolSnapshotSha256:'changed',approvedAt:row().reviewed_at,priorApprovals:approvals}),/prior approval/);
});
