import { studyHeadline, studyLede } from '@/lib/study-findings';
import { jsonLd, pageStructuredData } from '@/lib/server/public-data';
import Link from 'next/link';
import { listPolicyStudies } from '@/lib/server/policy-studies';
export const dynamic = 'force-dynamic';
export const metadata = { title: 'Head-to-head tests of ecommerce AI agents', description: 'Alhena Research Lab studies comparing ecommerce AI agents in live storefront chat widgets: policy-compliant resolution, answer quality and speed, with the evidence behind each score.', alternates: { canonical: '/studies' } };
export default function Page() {
  const studies = listPolicyStudies();
  return <main id="main" className="shell prose-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLd(pageStructuredData({ type: 'CollectionPage', path: '/studies', headline: 'Head-to-head tests of ecommerce AI agents', description: 'Separately versioned Alhena Research Lab studies of policy-compliant resolution, quality and speed in public storefront sessions.', crumbs: [{ name: 'Studies', path: '/studies' }] })) }} /><p className="eyebrow">ALHENA RESEARCH LAB</p><h1>Head-to-head tests of ecommerce AI agents</h1><p className="intro">Each study runs the same shopping and support conversations in real storefront chat widgets and scores resolution, answer quality and speed. Summaries are public; the conversations open with a verified work email.</p><p>This is a separately versioned Alhena Research Lab method. It is not the Gorgias leaderboard or the three-storefront quality pilot.</p><p><Link href="/studies/policy-resolution-v1">Read the versioned methodology</Link> · <Link href="/">Browse current research results</Link></p>{studies.length ? studies.map(study => <article className="method-card" key={study.slug}><h2><Link href={`/studies/${study.slug}`}>{studyHeadline(study)}</Link></h2><p>{studyLede(study)} {study.description}</p><p className="private-note">{study.protocol} · Published {study.publishedAt.slice(0, 10)}</p></article>) : <p className="notice">No policy-resolution study has been approved for publication. There are no public scores yet.</p>}</main>;
}
