"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,ArrowRight,RefreshCw} from "lucide-react";
import {Button} from "@/components/ui/button";
import {api,Vendor,date} from "@/lib/client";
import {ComparisonDetails} from "./request-flow";
type RequestRecord={id:string;status:string;providers:Vendor[];createdAt:string;updatedAt:string;reviewNote?:string;reportSlug?:string;error?:string};
const explanation:Record<string,string>={pending_review:"Your request is waiting for review. We’ll email you after a decision.",queued:"Your request has been approved and is queued for evaluation.",running:"The evaluation is capturing live conversations, judging responses and auditing the evidence. We’ll email you when the report is published.",judging:"The captured conversations are being scored against the published rubric.",auditing:"The scoring decisions are being audited before validation.",published:"The completed report is published. Its conversations and scoring evidence are available to explore.",rejected:"This request was not approved. See the reviewer’s note below.",failed:"The run could not complete. No incomplete comparison has been published. The operator has been notified.",needs_review:"This run needs the operator’s attention before it can proceed. No report has been published.",needs_adapter:"A storefront chat could not be tested reliably. The operator has been notified, and no report has been published."};
export function RequestStatus({id}:{id:string}){
 const [r,setR]=useState<RequestRecord|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 const load=()=>{setLoading(true);api<{request:RequestRecord}>(`/requests/${encodeURIComponent(id)}`).then(d=>{setR(d.request);setError("");}).catch(e=>setError(e.message)).finally(()=>setLoading(false));};
 useEffect(()=>{load();const timer=setInterval(load,30000);return()=>clearInterval(timer);},[id]);
 const index=r?.status==="published"?4:["pending_review","rejected"].includes(r?.status||"")?1:r?.status==="queued"?2:3;
 return <main id="main" className="shell prose-page"><Link href="/" className="back-link"><ArrowLeft size={16}/>Report library</Link><p className="eyebrow">YOUR COMPARISON REQUEST</p><h1>{r?r.providers.map(v=>v.name).join(" vs. "):"Request status"}</h1>{error?<div className="status-card"><div className="error-box" role="alert">{error}</div><p>Request details are private. If your session has expired, verify the same work email again to view this request.</p><Link className="button primary" href="/request">Verify work email <ArrowRight size={16}/></Link></div>:r?<><div className="status-header"><span className="status-label">{r.status.replaceAll("_"," ")}</span><span className="private-note">Submitted {date(r.createdAt)}</span></div><ol className="status-timeline">{["Email verified","In review","Approved","Evaluating","Published"].map((step,i)=><li key={step} className={i<=index?"reached":""}>{step}</li>)}</ol><div className="status-card"><h2>{r.status==="published"?"Your report is ready.":"We have your request."}</h2><p>{explanation[r.status]||"The request is being processed."}</p>{r.reviewNote&&<div className="request-scope"><strong>Reviewer’s note</strong><p>{r.reviewNote}</p></div>}{r.reportSlug&&<Link className="button primary" href={`/reports/${r.reportSlug}`}>Explore the report <ArrowRight size={16}/></Link>}<ComparisonDetails vendors={r.providers}/><Button variant="outline" disabled={loading} onClick={load}><RefreshCw size={15}/>{loading?"Refreshing…":"Refresh status"}</Button></div><p className="private-note">Only your verified session can view this request. Your name and email do not appear in published evidence.</p></>:<p role="status">Loading your request…</p>}</main>;
}
