"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
import Link from "next/link";
import {ArrowLeft,ArrowRight,Check,Mail,ShieldCheck,ExternalLink} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Checkbox} from "@/components/ui/checkbox";
import {InputOTP,InputOTPGroup,InputOTPSlot} from "@/components/ui/input-otp";
import {api,post,Vendor} from "@/lib/client";
type User={id:string;name:string;email:string};
const blank=():Vendor=>({name:"",website:"",customers:Array.from({length:3},()=>({name:"",website:""}))});
export function RequestFlow(){
 const [step,setStep]=useState(0),[user,setUser]=useState<User|null>(null),[name,setName]=useState(""),[email,setEmail]=useState(""),[code,setCode]=useState(""),[vendors,setVendors]=useState<Vendor[]>([blank(),blank()]),[notes,setNotes]=useState(""),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[requestId,setRequestId]=useState(""),[prior,setPrior]=useState<{id:string;status:string;providers:Vendor[]}[]>([]);
 useEffect(()=>{api<{user:User|null;requests:typeof prior}>("/auth/session").then(d=>{if(d.user){setUser(d.user);setEmail(d.user.email);setName(d.user.name);setStep(2);}setPrior(d.requests||[]);}).catch(()=>{});},[]);
 const lastStep=useRef(step);
 useEffect(()=>{if(lastStep.current!==step){lastStep.current=step;document.getElementById("flow-heading")?.scrollIntoView({block:"start"});}},[step]);
 async function run(action:()=>Promise<void>){setBusy(true);setError("");setNotice("");try{await action();}catch(e){setError(e instanceof Error?e.message:"Please try again.");}finally{setBusy(false);}}
 const start=(e?:FormEvent)=>{e?.preventDefault();run(async()=>{const d=await post<{message:string;delivery:string}>("/auth/start",{name,email});setStep(1);setCode("");setNotice(d.message);});};
 const verify=(e:FormEvent)=>{e.preventDefault();run(async()=>{const d=await post<{user:User}>("/auth/verify",{email,code});setUser(d.user);setStep(2);});};
 const patch=(index:number,field:"name"|"website",value:string,customer?:number)=>setVendors(old=>old.map((v,i)=>i!==index?v:customer===undefined?{...v,[field]:value}:{...v,customers:v.customers.map((c,j)=>j===customer?{...c,[field]:value}:c)}));
 const submit=()=>run(async()=>{const d=await post<{request:{id:string}}>("/requests",{providers:vendors,notes,consent});setRequestId(d.request.id);setStep(4);});
 const phase=step<=1?0:step===2?1:2;
 return <main id="main" className="shell request-page"><Link href="/" className="back-link"><ArrowLeft size={16}/>Report library</Link><div className="request-grid"><aside><p className="eyebrow">A NEW COMPARISON</p><h1>Put the answers<br/>to the test.</h1><p className="intro">Two providers. Three storefronts each.<br/>One published quality rubric.</p><ol className="steps">{["Verify your work email","Choose providers & storefronts","Review & submit"].map((s,i)=><li key={s} className={i===phase?"current":i<phase?"done":""}><span>{i<phase?<Check size={16}/>:i+1}</span>{s}</li>)}</ol><div className="aside-note"><ShieldCheck size={22}/><p>Every request is reviewed before testing starts. Approved comparisons use the same questions and scoring rules.</p><Link href="/methodology">Read the methodology <ExternalLink size={13}/></Link></div>{prior.length>0&&<div className="prior-requests"><h3>Your requests</h3>{prior.map(r=><Link key={r.id} href={`/requests/${r.id}`}>{r.providers.map(v=>v.name).join(" vs. ")}<small>{r.status.replaceAll("_"," ")}</small></Link>)}</div>}</aside>
 <section className="form-panel" aria-labelledby="flow-heading">{error&&<div className="error-box" role="alert">{error}</div>}{notice&&<p className="notice" role="status">{notice}</p>}
 {step===0&&<form onSubmit={start}><div className="form-icon"><Mail/></div><p className="eyebrow">STEP 01</p><h2 id="flow-heading">First, your work email.</h2><p className="muted">We’ll send a six-digit code to verify your mailbox. Your contact details stay private.</p><label className="field">Your name<Input required maxLength={100} autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Alex Morgan"/></label><label className="field">Work email<Input required type="email" maxLength={254} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="alex@company.com"/></label><p className="field-hint">Use your company email address. Personal and known disposable email addresses aren’t accepted.</p><Button className="primary-button full" disabled={busy}>{busy?"Requesting code…":"Send verification code"}<ArrowRight size={16}/></Button><p className="fine-print">We use your email for verification and request updates. <Link href="/privacy">Privacy policy</Link></p></form>}
 {step===1&&<form onSubmit={verify}><div className="form-icon"><Mail/></div><p className="eyebrow">CHECK YOUR INBOX</p><h2 id="flow-heading">Enter your verification code.</h2><p className="muted">Verification for <strong>{email}</strong>. The code expires in ten minutes.</p><label className="field" htmlFor="verification-code">Six-digit code</label><InputOTP id="verification-code" maxLength={6} pattern="^[0-9]*$" value={code} onChange={setCode} autoComplete="one-time-code" inputMode="numeric" aria-label="Six-digit verification code"><InputOTPGroup>{Array.from({length:6},(_,i)=><InputOTPSlot className="otp-cell" key={i} index={i}/>)}</InputOTPGroup></InputOTP><Button className="primary-button full" disabled={busy||code.length!==6}>{busy?"Verifying…":"Verify & continue"}<ArrowRight size={16}/></Button><div className="form-actions"><button type="button" className="text-button" disabled={busy} onClick={()=>start()}>Resend code</button><button type="button" className="text-button" onClick={()=>{setStep(0);setNotice("");}}>Use another email</button></div></form>}
 {step===2&&<form onSubmit={e=>{e.preventDefault();setError("");setStep(3);}}><div className="verified-line"><Check size={16}/>{user?.email} verified<button className="text-button" style={{marginLeft:"auto"}} type="button" onClick={()=>run(async()=>{await api("/auth/session",{method:"DELETE"});setUser(null);setPrior([]);setStep(0);})}>Sign out</button></div><p className="eyebrow">STEP 02</p><h2 id="flow-heading">What should we compare?</h2><p className="muted">Enter two AI providers and three customer storefronts where each is deployed. Include the exact storefront URLs where the live chat is available.</p>{vendors.map((v,i)=><fieldset className="vendor-fieldset" key={i}><legend><span>{i===0?"A":"B"}</span>Provider {i+1}</legend><div className="field-row"><label className="field">Provider name<Input required maxLength={100} value={v.name} onChange={e=>patch(i,"name",e.target.value)} placeholder={i===0?"e.g. Alhena":"e.g. Gorgias"}/></label><label className="field">Provider website<Input required type="url" maxLength={2048} value={v.website} onChange={e=>patch(i,"website",e.target.value)} placeholder="https://provider.com"/></label></div><p className="storefront-label">THREE CUSTOMER STOREFRONTS</p>{v.customers.map((c,j)=><div className="customer-row" key={j}><span className="customer-number">0{j+1}</span><label className="field">Customer name<Input required maxLength={100} aria-label={`Provider ${i+1}, customer ${j+1} name`} value={c.name} onChange={e=>patch(i,"name",e.target.value,j)} placeholder="Company name"/></label><label className="field">Storefront URL<Input required type="url" maxLength={2048} aria-label={`Provider ${i+1}, customer ${j+1} storefront URL`} value={c.website} onChange={e=>patch(i,"website",e.target.value,j)} placeholder="https://store.com"/></label></div>)}</fieldset>)}<label className="field">Anything the reviewer should know? <span className="optional">Optional</span><textarea rows={3} maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="For example, where to find the chat, regional storefront differences, or evidence of the provider deployment."/></label><Button className="primary-button full">Review comparison <ArrowRight size={16}/></Button></form>}
 {step===3&&<div><p className="eyebrow">STEP 03</p><h2 id="flow-heading">Ready for review.</h2><p className="muted">Check the companies and storefronts below. Approval authorizes one run of 12 conversations and 120 question-and-answer turns.</p><ComparisonDetails vendors={vendors}/>{notes&&<p className="review-note">{notes}</p>}<div className="request-scope"><strong>What happens next</strong><p>A reviewer checks your request. If approved, we email you and start the evaluation. A complete report that passes validation is published, and we email you its link. Incomplete or blocked runs do not publish.</p></div><label className="checkbox-label"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>I understand that this comparison, its storefronts and test evidence will be public if completed. My name and email remain private.</span></label><div className="form-actions"><Button variant="outline" disabled={busy} onClick={()=>setStep(2)}><ArrowLeft size={16}/>Edit details</Button><Button className="primary-button" disabled={busy||!consent} onClick={submit}>{busy?"Submitting…":"Submit for approval"}<ArrowRight size={16}/></Button></div></div>}
 {step===4&&<div className="success-panel"><span className="success-icon"><Check size={28}/></span><p className="eyebrow">REQUEST RECEIVED</p><h2 id="flow-heading">Your comparison is in review.</h2><p>We’ll email <strong>{email}</strong> after a decision, and again when a completed report is published.</p><Link className="button primary" href={`/requests/${requestId}`}>View request status <ArrowRight size={16}/></Link><Link className="text-link" href="/">Back to the report library</Link></div>}
 </section></div></main>;
}
export function ComparisonDetails({vendors}:{vendors:Vendor[]}){return <div className="comparison-details">{vendors.map((v,i)=><div key={i}><div className="provider-detail"><span className="provider-letter">{i===0?"A":"B"}</span><div><h3>{v.name}</h3><a href={safeUrl(v.website)} target="_blank" rel="noreferrer">{v.website}</a></div></div><ol>{v.customers.map((c,j)=><li key={j}><strong>{c.name}</strong><a href={safeUrl(c.website)} target="_blank" rel="noreferrer">{c.website}<ExternalLink size={13}/></a></li>)}</ol></div>)}</div>;}
function safeUrl(url:string){try{const u=new URL(url);return ["http:","https:"].includes(u.protocol)?u.href:undefined;}catch{return undefined;}}
